name: Package WoW Addon

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Addon ZIP
        run: |
          zip -r ChattyLittleNpc.zip ChattyLittleNpc

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ChattyLittleNpc.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
